on:
  workflow_dispatch:

jobs:
  twoms:
    name: 2MS Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run 2MS
        run: |
          docker run --rm \
            -v "$PWD":/repo \
            checkmarx/2ms \
            git /repo \
            --stdout-format sarif \
            --report-path /repo/artifacts/2ms.sarif \
            --ignore-on-exit results


